import: definition.yaml

concurrency:
  task:
    dbbench-std: 1
    os-std: 1
  agent:
    objectllama-7b: 1


assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - objectllama-7b
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
